In [1]:
import numpy as np


In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a.ndim

1

In [6]:
a.dtype

dtype('int32')

In [7]:
a = np.array([1,2,3,4], dtype = float)

In [8]:
a

array([1., 2., 3., 4.])

### multidimensional arrays

In [9]:
m = np.array([[1,2,3],
              [4, 5, 6],
              [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
m.ndim

2

In [11]:
m.dtype

dtype('int32')

In [12]:
m.itemsize

4

## linspace

In [13]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## reshape

In [15]:
m = np.array([[1,2],
             [3, 4],
             [5, 6]])

In [16]:
m.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
m.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [18]:
m.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [19]:
m.ravel() #flattening multi-dimensional array

array([1, 2, 3, 4, 5, 6])

In [20]:
m #but doesnt affect original array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
m.sum()

21

## operations

In [22]:
a = np.array([[1,2],
             [3,4]])

In [23]:
b = np.array([[5,6],
              [7,8]])

In [24]:
a+b

array([[ 6,  8],
       [10, 12]])

In [25]:
a*b

array([[ 5, 12],
       [21, 32]])

In [26]:
a+2*b

array([[11, 14],
       [17, 20]])

In [27]:
(a*b)[0]

array([ 5, 12])

In [28]:
(a*b)[0][0]

5

In [29]:
for x in a:
    print(x)

[1 2]
[3 4]


In [30]:
for x in a:
    for y in x:
        print(y)

1
2
3
4


In [32]:
for x in np.nditer(a):
    print(x)

1
2
3
4


In [33]:
s = np.array([1,2,3,4,5,6])

In [34]:
new = np.array_split(s, 4)

In [35]:
new

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [36]:
new = np.array_split(s, 5)

In [37]:
new

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

## searching an array

In [39]:
arr = np.array([1,2,3,4,5,4])
x = np.where(arr == 4)
print(x)

(array([3, 5], dtype=int32),)


In [40]:
y = np.searchsorted(arr, 6)
y #returns the index of the array where the number is to be inserted

6

In [42]:
arr1 = np.array([1,3,5,7])
y = np.searchsorted(arr1, [2,4,6])
y

array([1, 2, 3], dtype=int32)

In [43]:
np.sort(arr1)

array([1, 3, 5, 7])

In [44]:
arr2 = np.array([1,7,4,3,9,6])
np.sort(arr2)

array([1, 3, 4, 6, 7, 9])

In [48]:
ar = np.array([[1,6],
              [9,4],
              [2,7]])

In [49]:
np.sort(ar)

array([[1, 6],
       [4, 9],
       [2, 7]])

## filter arrays

In [51]:
arr = np.array([1,2,3,4,5,6,7,8])
filter_arr = []

for x in arr:
    if x%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False, True, False, True, False, True, False, True]
[2 4 6 8]


In [54]:
from numpy import random

In [57]:
new = random.permutation(arr)
new

array([[5, 6],
       [1, 2],
       [3, 4],
       [7, 8]])